// godot.js — plan the writes that put a sprite into a Godot project, as C# source.
//
// The odd one out, and deliberately. The other four targets hand over a PNG:
// adenosine, magnolia and texastoast read a uniform-grid sheet, and GameMaker
// takes the frames apart. This one writes no image at all.
//
// A .forge frame is already rows of single characters indexing a colour key,
// which transliterates straight into C#. Emitting that instead of a PNG buys
// three things a Godot project actually wants:
//
//   - No .import file. Godot generates one the first time it sees an image, in
//     the editor. Art that arrives as source is compiled with everything else,
//     so a fresh clone runs without opening the editor first.
//   - A recolour stays a one-line diff, the same as it is in the .forge.
//   - A game whose rule is that nothing loads from disk keeps it. very-long-boards
//     says exactly that about its procedural textures, and this is what let its
//     character art land without making an exception.
//
// ONE FRAME. A texture is one image; there is no sheet here to slice. A sprite
// with more frames exports its first and says so in a warning rather than
// silently dropping the rest — if you want an animation in Godot, the sheet
// targets are the right tool and AnimatedTexture is the right consumer.
//
// Pure, like the rest of core/: text in, plan out. It never touches a
// filesystem — the shell writes what this describes.

window.SpriteForge = window.SpriteForge || {};
window.SpriteForge.targets = window.SpriteForge.targets || {};
window.SpriteForge.targets.godot = (function () {

    const { hexToRgb } = window.SpriteForge.color;

    /** Where the generated classes land, matching what very-long-boards uses. */
    const DIR = 'Scripts/Art';
    const RUNTIME = 'ForgeArt.cs';
    const TRANSPARENT = '.';

    /**
     * A sprite name as a C# class name: carl_face -> CarlFace.
     *
     * Sprite names become filenames on export everywhere else in this app; here
     * they also become identifiers, which is a stricter thing to be. Anything
     * that is not a letter or digit is a separator, and a name starting with a
     * digit takes an `Art` prefix rather than producing a file that will not
     * compile.
     */
    function className(name) {
        const parts = String(name == null ? '' : name).split(/[^A-Za-z0-9]+/).filter(Boolean);
        const joined = parts.map(p => p[0].toUpperCase() + p.slice(1)).join('');
        if (!joined) return 'Art';
        return /^[0-9]/.test(joined) ? 'Art' + joined : joined;
    }

    /** 0..255 -> Godot's 0..1 float literal, three places, which is exact enough
     *  that a colour round-trips back to the same byte. */
    function chan(v) {
        return (v / 255).toFixed(3) + 'f';
    }

    /**
     * The decoder the generated classes call. Emitted alongside them because a
     * project that has the art and not this does not compile, and asking someone
     * to go and find it is a worse failure than writing a file they already have.
     * It is byte-identical every export, so rewriting it is a no-op.
     */
    function runtime() {
        return `using System.Collections.Generic;
using Godot;

/// <summary>
/// Decodes art authored in SPRITE//FORGE into a texture.
///
/// A .forge frame is rows of single characters indexing a shared colour key, which
/// transliterates straight into C#. That is why this art arrives as source rather than as a
/// PNG: there is no .import file for Godot to generate before the game will run, a recolour
/// stays a one-line diff, and a project whose rule is that nothing loads from disk keeps it.
///
/// GENERATED by SPRITE//FORGE's Godot export target. Re-export rather than editing it.
///
/// '.' is transparent, exactly as it is in the .forge.
/// </summary>
public static class ForgeArt
{
    public const char Transparent = '${TRANSPARENT}';

    /// <summary>
    /// Rows of key characters into an RGBA texture, one texel per character. The image is
    /// as wide as the first row and as tall as <paramref name="rows"/>.
    /// </summary>
    public static ImageTexture FromRows(string[] rows, Dictionary<char, Color> key)
    {
        int h = rows.Length;
        int w = rows[0].Length;
        var img = Image.CreateEmpty(w, h, false, Image.Format.Rgba8);

        for (int y = 0; y < h; y++)
        {
            string row = rows[y];
            // A short row would otherwise throw somewhere inside the loop with nothing saying
            // which row, and these are generated files that get re-exported.
            if (row.Length != w)
                GD.PushError($"ForgeArt: row {y} is {row.Length} characters, expected {w}");

            for (int x = 0; x < w && x < row.Length; x++)
            {
                char c = row[x];
                img.SetPixel(x, y, c == Transparent ? new Color(0, 0, 0, 0) : key[c]);
            }
        }

        return ImageTexture.CreateFromImage(img);
    }
}
`;
    }

    /**
     * One sprite as a C# class.
     *
     * The key holds only the colours the pixels actually use. A .forge carries
     * the whole editor palette whether the art touched it or not, and forty
     * unused Color literals in a generated file is noise a reader has to
     * discount every time they open it.
     */
    function source(cls, frame, w, h, forgeName) {
        const used = new Set();
        for (const row of frame) for (const px of row) if (px) used.add(px);
        const key = [...used].sort();

        const charOf = {};
        // Same alphabet order the .forge uses, so a file and its source agree on
        // which character is which colour and a diff of one predicts the other.
        const ALPHABET = window.SpriteForge.project.ALPHABET;
        key.forEach((hex, i) => { charOf[hex] = ALPHABET[i]; });

        const rows = frame.map(row =>
            row.map(px => (px ? charOf[px] : TRANSPARENT)).join(''));

        const keyLines = key.map((hex) => {
            const [r, g, b] = hexToRgb(hex);
            return `        ['${charOf[hex]}'] = new Color(${chan(r)}, ${chan(g)}, ${chan(b)}),   // ${hex}`;
        });

        return `using System.Collections.Generic;
using Godot;

/// <summary>
/// ${cls}, drawn in SPRITE//FORGE.
///
/// GENERATED from <c>${forgeName}</c> — re-export rather than editing a row here by hand.
/// ${w}x${h}, ${key.length} colour${key.length === 1 ? '' : 's'}.
/// </summary>
public static class ${cls}
{
    private static ImageTexture _texture;

    /// <summary>Built on first use and shared.</summary>
    public static ImageTexture Texture => _texture ??= ForgeArt.FromRows(Rows, Key);

    private static readonly Dictionary<char, Color> Key = new()
    {
${keyLines.join('\n')}
    };

    private static readonly string[] Rows =
    {
${rows.map(r => `        "${r}",`).join('\n')}
    };
}
`;
    }

    /**
     * Plans the writes for one sprite.
     *
     * @param name   sprite name; becomes both the class and the filename
     * @param frames pixel grids — only the first is written
     * @param w, h   frame size
     * @param dir    optional override for the destination directory
     * @returns {{ writes: Array<{path, text}>, snippet: string, warnings: string[] }}
     */
    function plan({ name, frames, w, h, dir }) {
        if (!frames || !frames.length) throw new Error(`${name}: no frames`);
        frames.forEach((f, i) => {
            if (f.length !== h || f.some(row => row.length !== w))
                throw new Error(`${name}: frame ${i} is not ${w}x${h}`);
        });

        const warnings = [];
        if (frames.length > 1)
            warnings.push(`${name}: ${frames.length} frames; a texture is one image, `
                + 'so only the first was written');

        const cls = className(name);
        const at = dir || DIR;
        const text = source(cls, frames[0], w, h, `${name}.forge`);

        return {
            // The runtime first: a project that got the art and not the decoder
            // does not compile, and the order is the order they are written in.
            writes: [
                { path: `${at}/${RUNTIME}`, text: runtime() },
                { path: `${at}/${cls}.cs`, text },
            ],
            snippet: `var mat = MeshKit.Mat(Colors.White, texture: ${cls}.Texture);`,
            warnings,
        };
    }

    /** Every sprite in a project, planned. The runtime is emitted once, not once
     *  per sprite — the same file written twice is not an error, but a plan that
     *  lists it five times reads like five different files. */
    function planProject({ project, dir }) {
        const writes = [], snippets = [], warnings = [];
        let runtimeDone = false;
        for (const s of project.sprites) {
            const p = plan({ name: s.name, frames: s.frames, w: s.w, h: s.h, dir });
            for (const wr of p.writes) {
                if (wr.path.endsWith(RUNTIME)) {
                    if (runtimeDone) continue;
                    runtimeDone = true;
                }
                writes.push(wr);
            }
            snippets.push(p.snippet);
            warnings.push(...p.warnings);
        }
        return { writes, snippet: snippets.join('\n'), warnings };
    }

    return { DIR, RUNTIME, className, runtime, source, plan, planProject };
})();
