// palettes.js — colour themes: the ones vendored from MAGMA//OPS, and yours.
//
// A theme here is only a named list of colours. It is not the app's own
// styling, and nothing in this file touches a pixel: it normalizes, validates
// and looks up, and that is all.
//
// Applying one is a different question and is not answered here. It used to
// replace the swatches you draw *from* and leave every pixel where it was,
// which meant the palette stopped describing the art the moment it was applied
// and the project quietly carried both sets of colours. It now offers to
// redraw the whole project in the theme, snapping each colour to the nearest
// one the theme has — core/project.js retheme() does the work and
// ui/project-ui.js asks the question, because it is the layer that knows every
// sprite rather than just the one on screen.
//
// The vendored set is data in core/ops-themes.js, generated by
// scripts/vendor-ops-themes.mjs. Custom themes are the same shape and arrive
// from wherever the shell keeps them — this file does not know or care, which
// is what keeps it pure and testable in Node with the rest of core/.
//
// The swatch cap is passed in rather than known here. It is the editor's
// number (MAX_SWATCHES), and core/sheet.js already takes it the same way.

window.SpriteForge = window.SpriteForge || {};
window.SpriteForge.palettes = (function () {

    const HEX = /^#[0-9a-f]{6}$/;

    /** Lowercased, valid, deduplicated, and no longer than `max`. */
    function normalize(colors, max) {
        const out = [];
        const seen = new Set();
        for (const c of colors || []) {
            const hex = String(c).trim().toLowerCase();
            if (!HEX.test(hex) || seen.has(hex)) continue;
            seen.add(hex);
            out.push(hex);
            if (max && out.length >= max) break;
        }
        return out;
    }

    /** True when `max` would cut the theme short, so the shell can say so
     *  rather than quietly handing over the first thirty-two of forty-nine. */
    function truncates(theme, max) {
        return !!max && normalize(theme.colors).length > max;
    }

    /** Throws unless this is a theme someone could actually load. */
    function validate(theme) {
        if (!theme || typeof theme !== 'object' || Array.isArray(theme))
            throw new Error('theme: not an object');
        if (typeof theme.name !== 'string' || !theme.name.trim())
            throw new Error('theme: name is empty');
        if (!Array.isArray(theme.colors))
            throw new Error(`${theme.name}: colors is not a list`);
        if (!normalize(theme.colors).length)
            throw new Error(`${theme.name}: no usable colours`);
        return theme;
    }

    /** A custom theme from a name and the swatches currently in the editor. */
    function custom(name, colors) {
        const theme = {
            id: 'custom:' + String(name).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            name: String(name).trim(),
            section: 'yours',
            colors: normalize(colors),
            custom: true,
        };
        return validate(theme);
    }

    /**
     * Whatever was stored, reduced to themes that will actually load.
     *
     * custom() validates on the way in, but nothing validated what came back
     * out, and this list is read while the editor is still starting up. One
     * malformed entry — or a stored value that is not a list at all — used to
     * throw there and take the rest of initialisation with it, leaving an app
     * with no canvas and no way back except clearing site data. Anything that
     * would not load is dropped instead of carried.
     */
    function sane(raw) {
        if (!Array.isArray(raw)) return [];
        return raw.filter(t => {
            try { validate(t); return true; } catch { return false; }
        });
    }

    /**
     * Every theme on offer: the vendored ones, then yours.
     *
     * Custom themes come last and win on id, so saving over a name you have
     * used before replaces it instead of listing it twice.
     */
    function list(customThemes) {
        const ops = (window.SpriteForge.opsThemes || [])
            .map(t => ({ ...t, custom: false }));
        const mine = [];
        const byId = new Map();
        for (const t of Array.isArray(customThemes) ? customThemes : []) {
            const c = { ...t, section: 'yours', custom: true };
            if (byId.has(c.id)) mine[byId.get(c.id)] = c;
            else { byId.set(c.id, mine.length); mine.push(c); }
        }
        return [...ops, ...mine];
    }

    function find(id, customThemes) {
        return list(customThemes).find(t => t.id === id) || null;
    }

    /** Themes grouped by section, in the order list() returns them, for a
     *  picker that wants optgroups. */
    function bySection(customThemes) {
        const groups = [];
        const index = new Map();
        for (const t of list(customThemes)) {
            if (!index.has(t.section)) {
                index.set(t.section, groups.length);
                groups.push({ section: t.section, themes: [] });
            }
            groups[index.get(t.section)].themes.push(t);
        }
        return groups;
    }

    return { normalize, truncates, validate, custom, sane, list, find, bySection };
}());
